### ISSUE TITLE
지출 통계 기능을 구현한다.

### ISSUE THREAD

**Issue by kwakmins** [kawkmin/smart_buget_craft#15]
## 📝 Description

`지출 통계`
1. 지난 달 대비 총액, 카테고리 별 소비율
    - 지난 달의 오늘 일차까지 해당하는 과거 모든 데이터 기록 대비
2. 지난 요일 대비 소비율
   - 오늘 요일에 해당되는 과거 모든 데이터 기록 대비
3. 다른 유저 대비 소비율
   - 다른 유저의 오늘에 해당하는 예산
   - 다른 유저의 소비율과 나의 소비율 대한 평균 비율

## ☑️ TODO

- [x] 지난 달 대비 총액, 카테고리 별 소비율 구현
- [x] 지난 요일 대비 소비율 구현
- [x] 다른 유저 대비 소비율 구현
