### ISSUE TITLE
예산 관련 Entity 및 DAO를 생성합니다.

### ISSUE THREAD

**Issue by kwakmins** [kawkmin/smart_buget_craft#8]
## 📝 Description

예산과 지출 카테고리 Entity 및 DAO를 생성합니다.

카테고리는 개발자가 임의로 설정합니다.

## ☑️ TODO

- [x] 예산 Entity 및 DAO 생성
- [x] 카테고리 Entity 및 DAO 생성
- [x] 카테고리 DB Init sql 파일 생성
